# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Specify the vagrant box to use
  config.vm.box = "chef/centos-7.0"
  config.vm.box_check_update = false

  # Forward port 8000: Default Django runserver port
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  # Forward port 5432: Default PostgreSQL port
  config.vm.network "forwarded_port", guest: 5432, host: 5432

  # Provider-specific configuration
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false

    # Customize the amount of memory on the VM
    vb.memory = "2048"
  end

  # Sync vagrant with project directory
  config.vm.synced_folder "../", "/application"

  # Provision vagrant box
  config.vm.provision :shell, path: "bootstrap.sh"

end
